name: Build & Release Static FFmpeg on macOS ARM

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-ffmpeg:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static FFmpeg (without GPL and non-free codecs)
        run: |
          SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg-minimal --build

      - name: check shared library
        run: |
          otool -L workspace/bin/ffmpeg

      - name: Copy ffmpeg binary
        run: |
          mkdir -p dist
          cp workspace/bin/ffmpeg dist/ffmpeg-macos-arm64
      
      - name: test run ffmepg
        run: |
          workspace/bin/ffmpeg -buildconf

      - name: Upload ffmpeg binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-arm64
          path: dist/ffmpeg-macos-arm64

      - name: Create GitHub Release and upload binary
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/ffmpeg-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}